# Project information
site_name: AI Robotics
site_url: https://luutp.github.io/review_ai_robotics/
site_author: TP-Luu
site_description: >-
  AI Robotics
# Repository
repo_name: luutp/review_ai_robotics
repo_url: https://github.com/luutp/review_ai_robotics
edit_uri: blob/develop/docs

# Copyright
copyright: Copyright &copy; 2021 Luu TP

# Configuration
theme:
    name: "material"
    custom_dir: material

    # Static files
    static_templates:
      - 404.html

    icon:
      repo: fontawesome/brands/github
    logo: images/jduck_logo.png
    favicon: images/favicon.ico

    font:
      text: Roboto #Incosolata
      code: Roboto Mono
    
    palette:      
      primary: orange
      accent: blue
    
    features:
      - navigation.expand
      - search.suggest
      - search.highlight

# Plugin
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
use_directory_urls: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luutp/review_ai_robotics
      name: review_ai_robotics Repo
  generator: false

extra_css:
  - css/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

### nav

### nav
